### ISSUE TITLE
Errors with 6.2.3, no two factor prompt for login

### ISSUE THREAD

**Issue by tedserreyn** [BGmot/zabbix#33] opened 2022-10-24 13:07 UTC
Get web page unavailable error.

I'm going to do a fresh install of 6.2.3 , then see if the web page works, then re-implement and see what happens.

**Comment by BGmot** [comment] 2023-05-14 12:10
Could not reproduce and 6.2 is not supported any longer. Closing this issue.

**Closed as completed by BGmot** 2023-05-14 12:10 UTC
